fun main() {
  println("Set")
  println("Inmutables")
  val numeros=setOf(1,2,3,4,5,6,5,3,4,2,1,1,3)
  println(numeros)
  println("Operaciones de Conjuntos")
  val pares=setOf(2,4,6,8,10)
  println("pares: $pares")
  val impares=setOf(1,3,5,7,9)
  val multiplos3=setOf(3,6,9,12)
  println("impares: $impares")
  println("union ${impares union pares}")
  println("interseccion ${impares intersect pares}")
  println("interseccion ${multiplos3 intersect pares}")
  println("substraccion ${impares subtract pares}")
  println("substraccion ${impares subtract multiplos3}")
  println("pares $pares")
  println("impares $impares")
  println("multiplos de 3 $multiplos3")
  
  
  println("Set")
  println("Mutables")
  
  val lenguajes = mutableSetOf("kotlin","java","reacnative")
  println(lenguajes)
  lenguajes.add("kotlin")
  println(lenguajes)
  lenguajes.add("javascript")
  println(lenguajes)
  lenguajes.remove("kotlin")
  println(lenguajes)
  println("Verificar si un valor existe ${"kotlin" in lenguajes}")
  println("Verificar si un valor existe ${"java" in lenguajes}")
}
